Use environment variable to authenticate to Google Drive
Metro-Records/la-metro-councilmatic pull request #1054
Opened 2024-01-05 14:48 UTC by antidipyramid

## Overview

This PR transitions the app to use an environment variable to authenticate to Google Drive rather than the current JSON file.

Connects Metro-Records/la-metro-dashboard#123 #1043

## Testing Instructions

 * Decrypt `configs/lametro_service_acct_key.json` and copy the contents to `GOOGLE_DRIVE_API_KEY` in `.env.local` (you'll have to move off this branch briefly to do + remove newline characters from the JSON string)
 * Set the `REMOTE_ANALYTICS_FOLDER` value in `.env.local` (you can use the value set in the staging app's Heroku env vars)
 * Run `python manage.py generate_tag_analytics`
 * Verify that the analytics file has been uploaded

2024-01-05 20:51 UTC, fgregg requested changes
should we also remove references to settings_deployment that are sprinkled about, or do you want to save that for a separate clean up PR?

2024-01-05 20:51 UTC, fgregg commented on councilmatic/settings.py
>  SERVICE_ACCOUNT_KEY_PATH = "configs/lametro_service_acct_key.json"
don't you want to remove this line?

2024-01-05 20:52 UTC, fgregg requested changes
we should be able to remove the keyrings directory altogether now.

2024-01-05 20:58 UTC, fgregg commented
> should we also remove references to settings_deployment that are sprinkled about, or do you want to save that for a separate clean up PR?

no, this should be done in a separate PR

2024-01-16 15:49 UTC, antidipyramid commented
@fgregg Any more comments on this one?

2024-01-16 15:50 UTC, fgregg approved these changes

2024-01-16 19:50 UTC, merged