Create and handle manual broadcasts for events
Metro-Records/la-metro-councilmatic pull request #1112
Opened 2024-05-29 13:45 UTC by xmedr

## Overview

Brief description of what this PR does, and why it is needed.

Connects #XXX

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

 * How to test this PR
 * Prefer bulleted description
 * Start after checking out this branch
 * Include any setup required, such as bundling scripts, restarting services, etc.
 * Include test case, and expected output

2024-06-03 20:23 UTC, hancush commented
@xmedr Want to have @antidipyramid take a look at this?

2024-06-03 20:24 UTC, xmedr commented
sounds good!

2024-06-06 19:03 UTC, antidipyramid requested changes
Great job on this one, @xmedr. Just one question inline.

What do you think about deploying to staging and testing the listen live links out during the next board/committee meeting?

2024-06-06 20:20 UTC, xmedr commented on lametro/templates/base.html
> +    {% get_events_with_manual_broadcasts as manual_events %}
makes sense!

2024-06-11 20:27 UTC, antidipyramid approved these changes

2024-06-28 13:54 UTC, merged