Fix duplicate search filters
Metro-Records/la-metro-councilmatic pull request #1180
Opened 2024-12-03 17:28 UTC by hancush

## Overview

The accessibility changes did not address an issue where search filters were duplicated. This PR applies a patch with the updated markup.

Connects #1009, #979 

### Demo

#### Before (Staging)

<img width="498" alt="Screenshot 2024-12-03 at 11 27 18 AM" src="https://github.com/user-attachments/assets/aa6c0daa-e245-45ff-86b1-e3b4fdcd112a">

#### After

<img width="502" alt="Screenshot 2024-12-03 at 11 26 40 AM" src="https://github.com/user-attachments/assets/3f643634-6fb1-430e-9b30-eb3523609dc9">

## Testing Instructions

- On the review app, view the search page and confirm all of the facets display correctly.
- Double check that the markup retains the accessibility changes (namely, data attributes and the aria-* attributes).

2024-12-03 18:30 UTC, xmedr requested changes
Ah ty for catching this! Looks good and the a11y changes are all intact. Just got one change in there

2024-12-03 18:30 UTC, xmedr commented on lametro/templates/search/_search_filter.html
> +                                    </a>
Voiceover is reading each facet link in the Meetings filter twice, and it looks like this produces nested links (which then resolves to just two links next to each other).

Removing the outermost anchor tag might be what we're looking for here. Maybe something like:

```html
<div class="skinny-list">
  {% if name in selected_facets.sponsorships %}
      <strong>{{ name | title }}</strong>
      <a href="#" class="remove-filter-value btn btn-primary btn-sm" data-param="{{facet_name}}_exact:{{name}}" aria-label="Remove {{name}} filter">
          <i class="fa fa-times" aria-hidden="true"></i>
      </a>
  {% else %}
      <a href="#" class="filter-value" data-param="sponsorships_exact:{{name}}" title="{{ name|title }}">
          {{ name | title }}
      </a>
  {% endif %}
</div>
```

2024-12-03 20:21 UTC, hancush commented
Great catch, thank you @xmedr! Patch in and ready for your eyeballs.

2024-12-04 14:30 UTC, xmedr approved these changes
This is perfect!

2024-12-04 19:11 UTC, merged