Implement board member details as snippet
Metro-Records/la-metro-councilmatic pull request #1189
Opened 2024-12-20 17:58 UTC by hancush

## Overview

tktktktk

Connects #XXX

### Demo

tktktk

### Notes

tktktktk

## Testing Instructions

tktktktk

2024-12-20 18:00 UTC, hancush commented on lametro/signals/handlers.py
> +@receiver(post_save, sender=LAMetroPerson)
Will handle instantiating details for new members moving forward. To backfill, we simply need to call save on all existing board members.

2024-12-20 18:01 UTC, hancush commented on lametro/models/cms.py
> +        return self._revisions
https://docs.wagtail.org/en/v5.2.7/topics/snippets/features.html#saving-draft-changes-of-snippets

2024-12-20 18:03 UTC, hancush commented on lametro/models/cms.py
> +        context["preview"] = True
The map and committee/board report modules require a bunch of extra context, so I use this to purposefully omit them from page previews. (I also added a note to the admin interface.)

2024-12-20 18:06 UTC, hancush commented on lametro/templates/snippets/related_object_status_tag.html
> +{% load wagtailadmin_tags %}
More or less stolen from the Wagtail source code, to make the status icon in the board member details snippet list link to the person detail page.

2024-12-20 18:08 UTC, hancush commented on lametro/wagtail_hooks.py
> +class BoardMemberFilterSet(django_filters.FilterSet):
This is a `django-filter` filter set, which I'm using to add custom filters for whether a person is a current board member and what body they belong to, on the board member detail snippet listing page.

2024-12-20 18:10 UTC, hancush commented on lametro/wagtail_hooks.py
> +class UserBarLink:
I pulled some reusable things out of the model admin link so I could also use them for the snippet edit link.

2024-12-20 18:10 UTC, hancush commented on lametro/wagtail_hooks.py
> +        return finder.get_edit_url(snippet)
TIL! https://docs.wagtail.org/en/latest/extending/admin_views.html#adminurlfinder

2025-01-07 20:48 UTC, xmedr requested changes
This looks really cool so far! Got a few a questions and comments below, but the status links and "edit this page" links work exactly as expected, and the whole editing process is smooth.

2025-01-07 20:48 UTC, xmedr commented on lametro/models/cms.py
> +        context["preview"] = True
The map currently isn't showing up on the non-preview version of the person detail page. This might be because it's on a review app that doesn't have access to `map_geojson` but wanted to make sure!

2025-01-22 14:35 UTC, hancush commented on lametro/models/cms.py
> +        context["preview"] = True
Great catch! The `populate_shapes` command (and, indeed, the whole release script) wasn't running, since this is a review app. I've added a new config variable, `WAGTAIL_STAGING`, a default to True for review apps in our CMS workstream, and a value of True for the actual Wagtail staging instance, so the release script will run there, too. The effect of all of this _should_ be that review apps created from branches where `WAGTAIL_STAGING` is set in `app.json` should run the release script, and so should the Wagtail staging deployment. Does that make sense?

2025-01-22 14:38 UTC, hancush commented on lametro/models/cms.py
> +        return f"{loaded_obj.person.name}{' (current)' if loaded_obj.person.current_memberships.exists() else ''}"
Excellent question. It _is_ useful when we know we'll be working with related objects! Any time you see yourself writing `{model}.{related_object}.{attribute}`, you should check the initial queryset to see whether you've loaded in that related object, in order to avoid the extra database queries. I did a lunch and learn on this way back in the day, when I was learning this lesson in a very painful way, lol: https://docs.google.com/document/d/1giTexSmZ0hXd1sPBU8AUuT_O2VWgpXaGqDZnMzW05kE/edit?usp=sharing

2025-01-22 14:39 UTC, hancush commented on lametro/models/cms.py
> +        return f"{loaded_obj.person.name}{' (current)' if loaded_obj.person.current_memberships.exists() else ''}"
It's extra useful when you're working in a loop, or if you're accessing multiple attributes from a related object.

2025-01-22 15:13 UTC, hancush commented on lametro/signals/handlers.py
> +@receiver(post_save, sender=LAMetroPerson)
Good idea! Signals aren't fired in migrations, so I added a `RunPython` step to the existing migration that creates detail pages for any members we already have in our database.

2025-01-22 15:42 UTC, hancush commented on docker-compose.yml
> -      SHARED_DB: "True"
Byeeee https://github.com/Metro-Records/scrapers-lametro/pull/35

2025-01-22 15:42 UTC, hancush commented on lametro/migrations/0018_boardmemberdetails.py
> +def initialize_detail_pages(apps, schema_editor):
Great suggestion, @xmedr!

2025-01-27 17:23 UTC, xmedr approved these changes
I got a couple error pages about relations not existing on the Pages and Board Member Details tabs when I first started up since a set of migrations did not automatically apply themselves. But after running `migrate` manually, everything worked as expected! It's probably because the `WAGTAIL_STAGING` env var wasn't set on this new review app.

This can come in, but what do you think about adding a note about that var in the readme of this or an upcoming pr, and then also adding that var in to subsequent review app configs as False?

2025-02-07 16:13 UTC, merged